### ISSUE TITLE
Cannot get bot to start - possibily due to proxy

### ISSUE THREAD

**Issue by jbmcfarlin31** [attzonko/mmpy_bot#106]
Hello, 

I am trying to start the bot and connect it to my mattermost server. I followed the directions on the main github page (the README) and have configured my mmpy_bot_settings.py file with the correct values. I cannot get the bot to start and I think it might be due to being behind a corporate proxy - however, I do have the appropriate `{http,https}_proxy` env vars set.

mmpy_bot_settings config:
```
SSL_VERIFY = False
BOT_URL = 'https://myurl.example.com/api/v4' 
BOT_LOGIN = 'mybot@email.com'
BOT_PASSWORD = 'password'
BOT_TEAM = 'testing' 
```

When I run the command: `MATTERMOST_BOT_SETTINGS_MODULE=mmpy_bot_settings mmpy_bot`, the following output appears:
```
[04/04/2019 16:19:36] connected to mattermost
[04/04/2019 16:19:36] loading plugin "mmpy_bot.plugins"
[04/04/2019 16:19:36] registered listen_to plugin "help_request" to "^!help$"
[04/04/2019 16:19:36] registered respond_to plugin "help_request" to "^!help$"
[04/04/2019 16:19:36] registered respond_to plugin "hello_reply" to "hello$"
[04/04/2019 16:19:36] registered listen_to plugin "hello_reply_formatting" to "hello_formatting$"
[04/04/2019 16:19:36] registered respond_to plugin "hello_reply_formatting" to "hello_formatting"
[04/04/2019 16:19:36] registered listen_to plugin "hello_send" to "hello$"
[04/04/2019 16:19:36] registered respond_to plugin "hello_decorators" to "hello_decorators"
[04/04/2019 16:19:36] registered listen_to plugin "hello_decorators" to "hello_decorators"
[04/04/2019 16:19:36] registered respond_to plugin "web_api_reply" to "hello_web_api"
[04/04/2019 16:19:36] registered listen_to plugin "hello_comment" to "hello_comment"
[04/04/2019 16:19:36] registered listen_to plugin "hello_react" to "hello_react"
[04/04/2019 16:19:36] registered listen_to plugin "hello_reply_threaded" to "hello_reply_threaded"
[04/04/2019 16:19:36] registered respond_to plugin "busy_reply" to "^busy|jobs$"
[04/04/2019 16:19:36] registered listen_to plugin "info_request" to "^!info$"
[04/04/2019 16:19:36] registered respond_to plugin "info_request" to "^!info$"
[04/04/2019 16:19:36] registered respond_to plugin "sleep_reply" to "sleep (.*)"
[04/04/2019 16:19:36] registered respond_to plugin "users_access" to "^admin$"
[04/04/2019 16:19:36] registered respond_to plugin "ping_reply" to "^ping$"
[04/04/2019 16:19:36] job running thread started
[04/04/2019 16:19:36] keep active thread started
```
After about a minute or so, the following exception occurs:
```
Traceback (most recent call last):
  File "/usr/local/bin/mmpy_bot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mmpy_bot/cli.py", line 18, in main
    b.run()
  File "/usr/local/lib/python2.7/dist-packages/mmpy_bot/bot.py", line 41, in run
    self._dispatcher.loop()
  File "/usr/local/lib/python2.7/dist-packages/mmpy_bot/dispatcher.py", line 133, in loop
    'user_removed']):
  File "/usr/local/lib/python2.7/dist-packages/mmpy_bot/mattermost.py", line 250, in messages
    if not self.connect_websocket():
  File "/usr/local/lib/python2.7/dist-packages/mmpy_bot/mattermost.py", line 237, in connect_websocket
    self._connect_websocket(url, cookie_name='MMAUTHTOKEN')
  File "/usr/local/lib/python2.7/dist-packages/mmpy_bot/mattermost.py", line 246, in _connect_websocket
    else ssl.CERT_NONE})
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 122, in connect
    sock = _tunnel(sock, hostname, port, auth)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 289, in _tunnel
    raise WebSocketProxyException(str(e))
websocket._exceptions.WebSocketProxyException: Connection is already closed.
```

I am running the following version of mmpy_bot: `1.3.4`

And the following version of mattermost: `Version: 5.8.0`

I am also running my mattermost behind an NGINX reverse proxy if that matters at all.

**Comment by attzonko** [comment]
Can you share your nginx proxy configuration? I run a very similar set up as well perhaps the websocket upgrade is not happening.

**Comment by jbmcfarlin31** [comment]
Server name and certs information has been redacted.

My proxy config is as follows:
```
upstream backend {
   server localhost:8065;
   keepalive 32;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=mattermost_cache:10m max_size=3g inactive=120m use_temp_path=off;

server {
   listen 80 default_server;
   server_name   myserver.example.com;
   return 301 https://$server_name$request_uri;
}

server {
   listen 443;
   server_name    myserver.example.com;

   ssl on;
   ssl_certificate /etc/nginx/certs/mycert.crt;
   ssl_certificate_key /etc/nginx/certs/mykey.key;
   ssl_session_timeout 1d;
   ssl_protocols TLSv1.2;
   ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
   ssl_prefer_server_ciphers on;
   ssl_session_cache shared:SSL:50m;
   # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
   add_header Strict-Transport-Security max-age=15768000;
   # OCSP Stapling ---
   # fetch OCSP records from URL in ssl_certificate and cache them
   ssl_stapling on;
   ssl_stapling_verify on;

   location ~ /api/v[0-9]+/(users/)?websocket$ {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       client_body_timeout 60;
       send_timeout 300;
       lingering_timeout 5;
       proxy_connect_timeout 90;
       proxy_send_timeout 300;
       proxy_read_timeout 90s;
       proxy_pass http://backend;
   }

   location / {
       client_max_body_size 50M;
       proxy_set_header Connection "";
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_cache mattermost_cache;
       proxy_cache_revalidate on;
       proxy_cache_min_uses 2;
       proxy_cache_use_stale timeout;
       proxy_cache_lock on;
       proxy_http_version 1.1;
       proxy_pass http://backend;
   }
}
```

**Comment by attzonko** [comment]
Here is my currently working one for reference:
```
upstream backend {
   server myserver.example.com:8065;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=mattermost_cache:10m max_size=3g inactive=120m use_temp_path=off;

server {
   listen 80;
   server_name   myserver.example.com;
   return 302 https://$server_name$request_uri;
}

server {
   listen 443 ssl http2;
   server_name    myserver.example.com;
   access_log /var/log/nginx/myserver.access.log;
   error_log /var/log/nginx/myserver.error.log;

   ssl on;
   ssl_certificate /etc/nginx/ssl/myserver.example.com.cer;
   ssl_certificate_key /etc/nginx/ssl/myserver_priv.pem.decrypted;
   ssl_session_timeout 5m;
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
   ssl_prefer_server_ciphers on;
   ssl_session_cache shared:SSL:10m;

   location ~ /api/v[0-9]+/(users/)?websocket$ {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 100M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_pass https://backend;
   }

   location / {
       client_max_body_size 100M;
       proxy_set_header Connection "";
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_cache mattermost_cache;
       proxy_cache_revalidate on;
       proxy_cache_min_uses 2;
       proxy_cache_use_stale timeout;
       proxy_cache_lock on;
       proxy_pass https://backend;
   }
}
```
I also have some environment variables exported from within the `activate` script for the bot virtual environment I used.

```
export REQUESTS_CA_BUNDLE=/etc/ssl/certs
export WEBSOCKET_CLIENT_CA_BUNDLE=/etc/ssl/certs
export http_proxy=http://proxy.example.com:33456
export https_proxy=http://proxy.example.com:33456
export no_proxy=example.com,myserver.example.com
```

**Comment by attzonko** [comment]
Also these are my redacted settings in bot_settings.py:
```
DEBUG = False
SSL_VERIFY = True
MATTERMOST_API_VERSION = 4
BOT_URL = 'https://myserver.example.com/api/v4' 
BOT_LOGIN = 'botname'
BOT_PASSWORD = 'bot_password'
BOT_TEAM = 'bot_team'
```

And this is how I start the bot from within a systemctl service file:
```
[Unit]
Description=Mattermost Bot (Bot_Name)
Requires=mattermost.service
After=mattermost.service

[Service]
Type=simple
ExecStart=/bin/bash -a -c "sleep 2 && source /bot_directory/bot_name/bin/activate && MATTERMOST_BOT_SETTINGS_MODULE=bot_settings mmpy_bot"
Restart=always
RestartSec=10
WorkingDirectory=/bot_directory/bot_name/
User=mattermost
Group=mattermost

[Install]
WantedBy=multi-user.target
```

**Comment by jbmcfarlin31** [comment]
So I compared my nginx conf to yours and there were very, very minimal differences. I commented out the ones that were in mine and not yours, but still seem to have the same problem. One thing I am not doing though is running mmpy_bot within virtualenv - is that something that is recommended?

**Comment by jbmcfarlin31** [comment]
Okay so I think it might have something to do with the way I am doing my reverse proxy... mattermost and the bot are installed on the same server locally. Due to the nature of our environment, there is a firewall in between my mattermost machine and the rest of the network with the mattermost port blocked (yes I could open it with a ticket to the team but to lazy lol). 

So the get around that, I reverse proxy'd the traffic over port 80/443 to that localhost:8065 port. For some reason mmpy_bot couldn't route that, so I ended up changing the bot_settings.py file.

I changed `BOT_URL = https://myserver.example.com/api/v4` to the following: `BOT_URL = http://localhost:8065/api/v4` and all is working. 

I did notice that the bot only starts when I run the `MATTERMOST_BOT_SETTINGS__MODULE=mmpy_bot_settings mmpy_bot` and when I CTRL+C out of it the bot stops. I would assume this is where running the bot as a service within virtualenv would come into play.

Is there documentation for getting that configured? Or perhaps could you walk through the way you set it up @attzonko?

**Comment by attzonko** [comment]
Actually I have the exact same set up where the bot and mattermost are running on the same server. And I don't need to specify the port explicitly, because the nginx reverse proxy takes care of it. But I think In the mattermost settings you need to specify the site URL. As far as the virtual envs, I do that in order to run multiple different bots with their own plugins, requiring their own set of python versions/modules. 

You can see one example of how to do that here:  https://mmpy-bot.readthedocs.io/en/latest/deploy.html

**Comment by jbmcfarlin31** [comment]
Awesome, thank you for the documentation link! I was able to get the bot working changing to localhost. I am not sure why I cannot use my actual fqdn name - but it's not to big of a worry right now, as this is only for testing and playing with.

Thank you for the insight and info!

**Comment by attzonko** [comment]
By the way the Site URL I have set includes the HTTPS port number, I think that was the key to getting it to work. So here are a couple of the values from my mattermost `config.json`

`"SiteURL": "https://myserver.example.com:443"`
and
`"ListenAddress": ":8065"`
