### ISSUE TITLE
Handling of --help is broken for click

### ISSUE THREAD

**Issue by sw-dbrown** [attzonko/mmpy_bot#339]
**Describe the bug**

**How To Reproduce**

- Create a bot with the listener provided in https://github.com/attzonko/mmpy_bot/issues/338
- Send the message `dummy --help`
- Observe that there is no response from the bot
- Observe the following error message in the bot's CLI log:
```
Usage: MyPlugin [OPTIONS]

Options:
  -a, --cmda TEXT  [required]
  -b, --cmdb TEXT  [required]
  --help           Show this message and exit.
[08/29/2022 10:04:26][mmpy.threadpool][ERROR] Unhandled exception in main loop
Traceback (most recent call last):
  File "/home/user/.local/git/misc/pyenv/versions/gitlab-projectbot/lib/python3.9/site-packages/mmpy_bot/threadpool.py", line 64, in handle_work
    function(*arguments)
  File "/home/user/.local/git/misc/pyenv/versions/gitlab-projectbot/lib/python3.9/site-packages/mmpy_bot/function.py", line 159, in __call__
    ctx = self.function.make_context(
  File "/home/user/.local/git/misc/pyenv/versions/gitlab-projectbot/lib/python3.9/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/home/user/.local/git/misc/pyenv/versions/gitlab-projectbot/lib/python3.9/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/user/.local/git/misc/pyenv/versions/gitlab-projectbot/lib/python3.9/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/user/.local/git/misc/pyenv/versions/gitlab-projectbot/lib/python3.9/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/home/user/.local/git/misc/pyenv/versions/gitlab-projectbot/lib/python3.9/site-packages/click/core.py", line 1274, in show_help
    ctx.exit()
  File "/home/user/.local/git/misc/pyenv/versions/gitlab-projectbot/lib/python3.9/site-packages/click/core.py", line 687, in exit
    raise Exit(code)
click.exceptions.Exit: 0
```

**Expected behavior**

The help message should be sent as a response.

Thanks for your time!

**Operating Environment (please complete the following information):**
 - mmpy_bot Version: mmpy_bot-2.1.0
 - mattermostdriver Version: mattermostdriver-7.3.2
 - Mattermost Server Version: 7.1.2
 - Python Version: 3.9.2
 - OS: Linux

**Additional context**
Add any other context about the problem here [e.g. Settings for your bot, API Version]

**Comment by unode** [comment]
Hi @sw-dbrown this was fixed in https://github.com/attzonko/mmpy_bot/commit/f6d8b9809dc86d3c4e027c4278f94435594fe985 which hasn't been released yet. Would you mind trying the latest version from the `main` branch and see if the problem persists?

**Comment by sw-dbrown** [comment]
Hey @unode, thanks for the very fast response. I just manually applied the patch in my venv and I can confirm that the issue is fixed in https://github.com/attzonko/mmpy_bot/commit/f6d8b9809dc86d3c4e027c4278f94435594fe985. Is it intended behavior that the output of the `--help` command is also sent to the log of the bot?

> Hi @sw-dbrown this was fixed in [f6d8b98](https://github.com/attzonko/mmpy_bot/commit/f6d8b9809dc86d3c4e027c4278f94435594fe985) which hasn't been released yet. Would you mind trying the latest version from the `main` branch and see if the problem persists?

**Comment by unode** [comment]
Not intended but harder to control as it's pre-defined behavior in `click`.
There may be a workaround but the crash was the most important part.

Either way, I would discourage the use of `--help` as we can't easily control the content of the output.

**Comment by attzonko** [comment]
So the remaining issue is that with plugins which use 'click' functions, when the plugin gets the '_--help_' command, the output shows up in the channel and also in the log?

**Comment by unode** [comment]
The output is sent to stdout stream, not really the log.

**Comment by attzonko** [comment]
I am fine leaving it as is....its a side effect of 'click' :)
