### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by JacobCoffee** [attzonko/mmpy_bot#466]
## Issue

I believe I am hitting an issue with reverse proxy here, but I'm not sure how to resolve.. I am shooting long here because from what I can find it might be something to do with the way our reverse proxy is set up and unfortunately I am not privy to the setup besides it being clustered with k8s deployment.

Do you have any advice for me? Sorry for not being able to provide the whole config. I would've rather opened a discussion as it's most likely a 'me' problem 😅 

<details>

<summary>Error log</summary>

```shell
[12/05/2023 16:47:32][mmpy.bot][INFO] Starting bot Bot.
[12/05/2023 16:47:32][mmpy.plugin_base][DEBUG] Plugin MyPlugin started!
[12/05/2023 16:47:32][mmpy.threadpool][INFO] Scheduler thread started.
[12/05/2023 16:47:32][asyncio][DEBUG] Using selector: KqueueSelector

[12/05/2023 16:47:32][mattermostautodriver.websocket][ERROR] Failed to establish websocket connection: <class 'aiohttp.client_exceptions.WSServerHandshakeError'> thrown
Traceback (most recent call last):
  File "/Users/user/git/internal/bucket/repo/.venv/lib/python3.11/site-packages/mattermostautodriver/websocket.py", line 54, in connect
    async with session.ws_connect(
  File "/Users/user/git/internal/bucket/repo/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Users/user/git/internal/bucket/repo/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 821, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://mattermost.company.com:443/websocket')

[12/05/2023 16:47:37][mattermostautodriver.websocket][ERROR] Failed to establish websocket connection: <class 'aiohttp.client_exceptions.WSServerHandshakeError'> thrown
Traceback (most recent call last):
  File "/Users/user/git/internal/bucket/repo/.venv/lib/python3.11/site-packages/mattermostautodriver/websocket.py", line 54, in connect
    async with session.ws_connect(
  File "/Users/user/git/internal/bucket/repo/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Users/user/git/internal/bucket/repo/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 821, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://mattermost.company.com:443/websocket')
```

</details>

## Reproduce
Give us simple steps to reproduce the behavior:
1. Run `app.py` below, but with my particular deployment... kind've hard 😓 

## Expected Behavior
Connection not to fail

## Environment
 - mmpy_bot Version: `2.1.4`
 - mattermostdriver/mattermostautodriver Version: `1.2.4`
 - Mattermost Server Version: `7.1.5`
 - Python Version: `3.11`
 - OS: `MacOS`

## Extra Details
Add any other context about the problem here [e.g. Settings for your bot, API Version]

```py
"""Entrypoint for bot."""
from mmpy_bot import Bot, Message, Plugin, Settings, listen_to


class MyPlugin(Plugin):
    @listen_to("wake up")
    async def wake_up(self, message: Message):
        self.driver.reply_to(message, "I'm awake!")


if __name__ == "__main__":
    bot = Bot(
        settings=Settings(
            MATTERMOST_URL="https://mattermost.company.com",  # this points to 3-4 clustered hosts.
            MATTERMOST_API_PATH="", # not setting this duplicates /api/v4?
            BOT_TOKEN="SomeToken",
            BOT_TEAM="My_team",
            SSL_VERIFY=False,
            RESPOND_CHANNEL_HELP=True,
            DEBUG=True,
        ),
        plugins=[MyPlugin()],
    )

    bot.run()
    ```

**Comment by JacobCoffee** [comment]
After working with my team on this (they tried adjusting some things found in MM forums), I tried to downgrade the driver - but realized it was on 1.2.x and the latest was 2.0.

I `pip install mattermostautodriver==1.3.0` and things now work

```console
[12/06/2023 12:15:56][mmpy.bot][INFO] Starting bot Bot.
[12/06/2023 12:15:56][mmpy.plugin_base][DEBUG] Plugin APIPlugin started!
[12/06/2023 12:15:56][asyncio][DEBUG] Using selector: KqueueSelector
[12/06/2023 12:15:56][mmpy.threadpool][INFO] Scheduler thread started.
[12/06/2023 12:15:56][mattermostautodriver.websocket][INFO] Websocket authentification OK
```

Recommend maybe bumping this?

**Comment by unode** [comment]
Hi @JacobCoffee,

Apologies for the confusion. Indeed for mattermostautodriver 1.3.0 we need the changes introduced in https://github.com/attzonko/mmpy_bot/commit/0e553af96b463b59a272d535e11a38b302640dec which aren't released yet. 

There's also a new version of mmautodriver (2.0.0) that introduced potential additional incompatibilities, we'll need to test if that version remains compatible with mmpy_bot core as it introduced [quite some API changes](https://github.com/embl-bio-it/python-mattermost-autodriver/blob/main/CHANGELOG.rst#200). We'll do that transition in a future release.

The mattermostautodriver project closely tries to follow the [mattermost API specification](https://api.mattermost.com/) so any upstream changes are propagated downwards. There is no backwards incompatibility layer in that project.
We are trying to proceed cautiously from mmautodriver 1.3.0 onwards, taking into account [that project's versioning scheme](https://github.com/embl-bio-it/python-mattermost-autodriver#versions-and-releases).

**Comment by JacobCoffee** [comment]
Thank you :)
