### ISSUE TITLE
Could not get the bot working.

### ISSUE THREAD

**Issue by attzonko** [attzonko/mmpy_bot#59]
I am adding this issue based on getting a direct e-mail contact. Will ask the submitter to provide additional information here, so we can track it. I decided to add this myself as it seemed like a good first issue someone might have.

**Describe the bug**
I switched from Slack to Mattermost and like to use this bot to archive some tasks.
But sadly i failed to add a command. (I just did some basic stuff in python right automation.)

**How To Reproduce**

1. create a file in ~/mmpy_bot/mmpy_bot/plugins/intro.py
2. Adding following content in the file:
```
import re
from mmpy_bot.bot import listen_to
from mmpy_bot.bot import respond_to 
@respond_to('^\!introduce$')
@listen_to('^\!introduce$')
def introduce(message):
    message.reply('Hello i am a bot.')
```
3. Start the Bot, with  `cd ~/mmpy_bot; MATTERMOST_BOT_SETTINGS_MODULE=local_settings mmpy_bot`

4. Got this Error

```
[08/06/2018 15:04:58] registered listen_to plugin "hello_react" to "hello_react"
[08/06/2018 15:04:58] No module named 'mmpy_bot.plugins.intro'
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mmpy_bot/bot.py", line 82, in _load_plugins
    _module = importlib.import_module(module)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'mmpy_bot.plugins.intro'
[08/06/2018 15:04:58] keep active thread started
```
5. Even when i add the command to `hello.py` i get an error:

` Bad command "!introduce", Here is what I currently know how to do:`

**Expected behavior**
The bot to listen and respond to the keyword 'introduce' and respond with "Hello i am a bot."

**Operating Environment (please complete the following information):**
 - OS: ???
 - Python Version: 3.4
 - Mattermost Version: ???
 - mmpy_bot Version: ???

**Comment by seLain** [comment]
Looks like an importing path issue.

It would be better if the submitter can also provide 
- python `sys.path` info, 
- the `PLUGINS` configuration in `local_settings.py`, 
- and exactly where `intro.py` is located ( inside `PYTHON_HOME/site-packages/mmpy_bot...` or ? )

**Comment by r00tbox** [comment]
**Missing version numbers**
- OS: CentOS 7
- Mattermost: 5.1.0
- mmy_bot: 1.2.1

**sys.path**
`print(sys.path)
['', '/usr/lib64/python34.zip', '/usr/lib64/python3.4', '/usr/lib64/python3.4/plat-linux', '/usr/lib64/python3.4/lib-dynload', '/usr/lib64/python3.4/site-packages', '/usr/lib/python3.4/site-packages']
`

**Plugins**
`PLUGINS = [
    'mmpy_bot.plugins',
]
`

**intro.py location**
`~/mmpy_bot/mmpy_bot/plugins/intro.py`

**Comment by seLain** [comment]
Try this : 
- relocate `intro.py` to `~/mmpy_bot/my_plugins/intro.py`
- add  `~/mmpy_bot/my_plugins/__init__.py` as an empty file
- set `PLUGINS = [ 'mmpy_bot.plugins', 'my_plugins' ]` in `~/mmpy_bot/local_settings.py` ( I assume you put `local_settings.py` under `~/mmpy_bot/`

The file structure will be like this : 
```
~/mmpy_bot
    ......
    docs/
    mmpy_bot/
    my_plugins/
    ......
    local_settings.py
    README
    ......
```
And run your `mmpy_bot` command again, see if it works.

**Comment by r00tbox** [comment]
This worked!

i plan to put the bot when it's final to /opt or is it recommendet to put it in PYTHON_HOME/site-packages?

**Comment by seLain** [comment]
I will not put customized plugins in `site-packages`. It might cause unpredictable issues when you updating `mmpy_bot`.

If you put bot in `/opt`, just make sure you include `/opt/your_bot/` in `PYTHONPATH` environment variable. That tells python where to look for `my_plugins`.

Btw, you don't have to keep all `mmpy_bot` source if you simply want to add some plugins ( listen_to, respond_to handlers). You can have `/opt/your_bot/` like this :
```
~/opt/your_bot/
    my_plugins/
        __init__.py
        intro.py
        .....
    local_settings.py
```
That should be enough.

And if you don't need default plugins, set `PLUGINS = [ 'my_plugins',]` without 'mmpy_bot.plugins'.

**Comment by attzonko** [comment]
Thanks @seLain for helping with this. I think we can close the issue at this point.
