### ISSUE TITLE
Fail to start Bot if settings contain non-ASCII characters

### ISSUE THREAD

**Issue by a3dho3yn** [attzonko/mmpy_bot#70]
**Describe the bug**
If settings module contains non-ASCII characters, Bot will fail to start.

**How To Reproduce**
In the settings module, set `DEFAULT_REPLY = "سلام"`.

**Operating Environment:**
 - OS: Windows 10 and Ubunutu 16.04
 - Python Version: 3.6
 - Mattermost Version: 4.10
 - mmpy_bot Version: 1.3.0

**Trace**
```
Traceback (most recent call last):
  File "src\bot.py", line 5, in <module>
    from mmpy_bot.bot import Bot, MattermostClient, PluginsManager,\
  File "%PROJECT_PATH%\assistant-bot\venv\src\mmpy-bot\mmpy_bot\bot.py", line 15, in <module>
    from mmpy_bot import settings
  File ""%PROJECT_PATH%\assistant-bot\venv\src\mmpy-bot\mmpy_bot\settings.py", line 62, in <module>
    exec(open(filename).read())
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 303: character maps to <undefined>
```

**Comment by seLain** [comment]
hi @a3dho3yn , thanks for reporting this bug.

It seems that in `settings.py`,  the `local_settings.py` file should be opened with `encoding="utf-8"`
```python
if settings_module is not None:
    pwd = os.getcwd()
    if pwd not in sys.path:
        sys.path.insert(0, pwd)
    settings = importlib.import_module(settings_module)
    filename = settings.__file__.replace('.pyc', '.py')
    try:
        execfile(filename)
    except NameError:
!       exec(open(filename, encoding='utf-8').read())
```
That should fix this issue. 
I will make a PR later.

**Comment by seLain** [comment]
@a3dho3yn  The fix was merged. Please help us check if it works out, thanks :)

**Comment by a3dho3yn** [comment]
It works fine. Thanks 👍
