### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zolij** [attzonko/mmpy_bot#76]
Hi,

I tried a basic example, but I get error for some messages.

```
Unhandled exception in thread started by <bound method WorkerPool.do_work of <mmpy_bot.utils.WorkerPool object at 0x7f963c061d30>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mmpy_bot/utils.py", line 31, in do_work
    self.func(msg)
  File "/usr/local/lib/python3.7/site-packages/mmpy_bot/dispatcher.py", line 103, in dispatch_msg
    self._default_reply(msg)
  File "/usr/local/lib/python3.7/site-packages/mmpy_bot/dispatcher.py", line 151, in _default_reply
    key = v.__module__.title().split('.')[1]
IndexError: list index out of range
```

My code:

```
import re
from mmpy_bot.bot import Bot
from mmpy_bot.bot import listen_to
from mmpy_bot.bot import respond_to


@respond_to('hi', re.IGNORECASE)
def hi(message):
    message.reply('I can understand hi or HI!')


@respond_to('I love you')
def love(message):
    message.reply('I love you too!')


@listen_to('Can someone help me?')
def help_me(message):
    message.reply('Yes, I can!')


if __name__ == "__main__":
    Bot().run()
```

What am I missing?

Thanks

**Comment by seLain** [comment]
hi @zolij , thanks for spotting this issue.
I merged a fix at PR #77 . 
Please check out latest master branch and install it by `python setup.py install`. 
See if it works on your bot code.

I will not recommend putting `listen_to` and `respond_to` handlers in `__main__` module though.
Maybe you would like to organize handlers and local_settings as illustrated in #59 .
