### ISSUE TITLE
socket.error websocket exception isn't handled

### ISSUE THREAD

**Issue by ebardsley** [attzonko/mmpy_bot#78]
**Describe the bug**
socket.error websocket exception isn't handled

**How To Reproduce**
Take down the mattermost server unexpectedly, I think.

**Expected behavior**

**Operating Environment (please complete the following information):**
 - OS: Linux
 - Python Version: 2.7
 - Mattermost Version: ???
 - mmpy_bot Version: f622994
 
**Additional context**
```
Unhandled exception in thread started by <bound method Bot._keep_active of <mmpy_bot.bot.Bot object at 0x7f1482553d90>>
--
Traceback (most recent call last):
File "/var/tmp/src/mmpy-bot/mmpy_bot/bot.py", line 45, in _keep_active
self._client.ping()
File "/var/tmp/src/mmpy-bot/mmpy_bot/mattermost.py", line 262, in ping
self.websocket.ping()
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 281, in ping
self.send(payload, ABNF.OPCODE_PING)
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 240, in send
return self.send_frame(frame)
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 265, in send_frame
l = self._send(data)
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 430, in _send
return send(self.sock, data)
File "/usr/local/lib/python2.7/dist-packages/websocket/_socket.py", line 117, in send
return sock.send(data)
File "/usr/lib/python2.7/ssl.py", line 687, in send
v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe
```

**Comment by seLain** [comment]
Thanks for reporting this issue.
Exception handling for socket.error was added #79
